"""fix models

Revision ID: c058674a3742
Revises: 434a97b2e4ad
Create Date: 2024-12-13 15:01:12.743012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c058674a3742'
down_revision = '434a97b2e4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
